#!/bin/bash

# Enhanced preview script for Kobo Recap AI-generated content
# This script allows you to view the recap and character information 
# generated by the AI before uploading to Kobo

echo "=== Enhanced Kobo Recap AI Content Preview ==="
echo ""

# Check if we have cached paths from previous runs
if [ -f "$HOME/.kobo_recap_paths" ]; then
    source "$HOME/.kobo_recap_paths"
fi

# Get books directory path (ask user if not set)
if [ -z "$BOOKS_DIR" ]; then
    echo "Please specify the directory where your kepub books are stored:"
    echo "(Example: /path/to/your/books/)"
    read -p "Books directory path: " BOOKS_DIR
    # Validate the directory exists
    if [ ! -d "$BOOKS_DIR" ]; then
        echo "Error: Directory '$BOOKS_DIR' does not exist."
        exit 1
    fi
    # Save for future runs
    echo "BOOKS_DIR=\"$BOOKS_DIR\"" > "$HOME/.kobo_recap_paths"
fi

# Check if arguments are provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 \"Book Title - Author.kepub.epub\""
    echo ""
    echo "Available books in your collection:"
    find "$BOOKS_DIR" -name "*.kepub.epub" -type f | xargs -n1 basename | head -10
    exit 1
fi

BOOK_FILE="$1"

# Validate that the file exists in the expected location
BOOK_PATH="$BOOKS_DIR/$BOOK_FILE"

if [ ! -f "$BOOK_PATH" ]; then
    echo "Error: Could not find $BOOK_FILE in your books directory"
    echo ""
    echo "Available books in your collection:"
    find "$BOOKS_DIR" -name "*.kepub.epub" -type f | xargs -n1 basename | head -10
    echo ""
    echo "Please check the filename and try again."
    exit 1
fi

echo "Previewing content for: $BOOK_FILE"
echo ""

# Create temporary directory for extraction
TEMP_DIR="/tmp/recap_preview_$$"
mkdir -p "$TEMP_DIR"

echo "Extracting book content..."

# Copy the book to working directory
cp "$BOOK_PATH" "$TEMP_DIR/original.kepub.epub"

# Navigate to working directory and unzip
cd "$TEMP_DIR"
unzip -q original.kepub.epub

echo ""
echo "=== CHECKING BOOK STRUCTURE ==="

# Show what files are available in the book
echo "Files found in book structure:"
find . -type f | sort | head -20

echo ""
echo "=== CHECKING FOR RECAP DIRECTORIES ==="

# Check if recap directory exists
if [ -d "EPUB/recaps" ]; then
    echo "✓ Recap directory found!"
    ls -la "EPUB/recaps"
    
    # Check for the specific TSV files
    echo ""
    echo "=== CONTENT OF RECAP FILES ==="
    
    if [ -f "EPUB/recaps/recaps.tsv" ]; then
        echo ""
        echo "Chapter Summaries (recaps.tsv):"
        echo "================================"
        head -20 "EPUB/recaps/recaps.tsv"
    else
        echo "No recaps.tsv file found"
    fi
    
    if [ -f "EPUB/recaps/cast.tsv" ]; then
        echo ""
        echo "Character Profiles (cast.tsv):"
        echo "==============================="
        head -20 "EPUB/recaps/cast.tsv"
    else
        echo "No cast.tsv file found"
    fi
    
else
    echo "✗ No recap directory found in book structure."
    echo "This might be because:"
    echo "1. The book was not processed with AI (or failed to create AI content)"
    echo "2. The book has an older format without recap support"
    echo "3. There was an error during processing that prevented files from being written"
fi

echo ""
echo "=== CHECKING AI CONFIGURATION ==="
if [ -f "$HOME/.kobo_recap_ai_config" ]; then
    echo "AI configuration found:"
    cat "$HOME/.kobo_recap_ai_config"
else
    echo "No AI configuration found."
fi

echo ""
echo "=== PREVIEW COMPLETE ==="
echo ""

# Clean up
cd - > /dev/null
rm -rf "$TEMP_DIR"

echo "Preview complete. The content above shows what recap information was found in the book."
echo "If you see TSV files, they contain the AI-generated chapter summaries and character profiles."
echo ""
echo "To regenerate this book with AI processing:"
echo "./scripts/prepare_book_for_recap_ai.sh \"$BOOK_FILE\""